# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_neighborhoods_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listingId', models.IntegerField(default=0)),
                ('location', models.CharField(default='SF', max_length=255)),
                ('long', models.DecimalField(decimal_places=3, max_digits=8)),
                ('lat', models.DecimalField(decimal_places=3, max_digits=8)),
                ('property_type', models.CharField(default='N/A', max_length=30)),
                ('room_type', models.CharField(default='N/A', max_length=30)),
                ('accommodates', models.IntegerField(default=0)),
                ('bed_type', models.CharField(default='N/A', max_length=30)),
                ('price_night', models.DecimalField(decimal_places=3, max_digits=8)),
                ('price_cleaning', models.DecimalField(decimal_places=3, max_digits=8)),
                ('host_response_time', models.CharField(default='N/A', max_length=30)),
                ('host_response_rate', models.IntegerField(default=0)),
                ('host_is_superhost', models.BooleanField(default=False)),
                ('host_has_profile_pic', models.BooleanField(default=False)),
                ('host_identity_verified', models.BooleanField(default=False)),
                ('host_since', models.DateField()),
                ('score_overall', models.IntegerField(default=0)),
                ('score_location', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='neighborhoods',
            name='name',
            field=models.CharField(default='area', max_length=255),
        ),
    ]
