# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20171108_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='host_since',
            field=models.DateField(default='1998-01-02'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='lat',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='listing',
            name='long',
            field=models.DecimalField(decimal_places=15, default=0.0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price_cleaning',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price_night',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=8),
        ),
    ]
