# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20171108_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='neighborhood',
            field=models.CharField(default='SF', max_length=255),
        ),
    ]
