# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_listing_neighborhood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='neighborhood',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
