# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-08 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20171108_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='total_places_in_neighborhood',
            field=models.IntegerField(default=1),
        ),
    ]
